root -l -b -q 'HbbHbb_KinematicSelection.cc++("Signal_V42_V8", "RadionToHH_4b_M-270_TuneZ2star_8TeV_FULLSIM")'
root -l -b -q 'HbbHbb_KinematicSelection.cc++("Signal_V42_V8", "RadionToHH_4b_M-300_TuneZ2star_8TeV_FULLSIM")'
root -l -b -q 'HbbHbb_KinematicSelection.cc++("Signal_V42_V8", "RadionToHH_4b_M-350_TuneZ2star_8TeV_FULLSIM")'
root -l -b -q 'HbbHbb_KinematicSelection.cc++("Signal_V42_V8", "RadionToHH_4b_M-400_TuneZ2star_8TeV_FULLSIM")'
root -l -b -q 'HbbHbb_KinematicSelection.cc++("Signal_V42_V8", "RadionToHH_4b_M-450_TuneZ2star_8TeV_FULLSIM")'
root -l -b -q 'HbbHbb_KinematicSelection.cc++("Signal_V42_V8", "RadionToHH_4b_M-500_TuneZ2star_8TeV_FULLSIM")'
root -l -b -q 'HbbHbb_KinematicSelection.cc++("Signal_V42_V8", "RadionToHH_4b_M-550_TuneZ2star_8TeV_FULLSIM")'
root -l -b -q 'HbbHbb_KinematicSelection.cc++("Signal_V42_V8", "RadionToHH_4b_M-600_TuneZ2star_8TeV_FULLSIM")'
root -l -b -q 'HbbHbb_KinematicSelection.cc++("Signal_V42_V8", "RadionToHH_4b_M-650_TuneZ2star_8TeV_FULLSIM")'
root -l -b -q 'HbbHbb_KinematicSelection.cc++("Signal_V42_V8", "RadionToHH_4b_M-700_TuneZ2star_8TeV_FULLSIM")'
root -l -b -q 'HbbHbb_KinematicSelection.cc++("Signal_V42_V8", "RadionToHH_4b_M-800_TuneZ2star_8TeV_FULLSIM")'
root -l -b -q 'HbbHbb_KinematicSelection.cc++("Signal_V42_V8", "RadionToHH_4b_M-900_TuneZ2star_8TeV_FULLSIM")'
root -l -b -q 'HbbHbb_KinematicSelection.cc++("Signal_V42_V8", "RadionToHH_4b_M-1000_TuneZ2star_8TeV_FULLSIM")'
root -l -b -q 'HbbHbb_KinematicSelection.cc++("Signal_V42_V8", "RadionToHH_4b_M-1100_TuneZ2star_8TeV_FULLSIM")'
say "Kinematic selection of signal Monte Carlo done."
